version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x nodejs qtdeclarative5-dev g++ xvfb zip
      - gem install bundler
  pre_build:
    commands:
      - bundle install
      - "bundle exec rake db:create"
      - "bundle exec rake db:migrate"
  build:
    commands:
      - bundle exec rspec
      - xvfb-run --auto-servernum bundle exec cucumber
  post_build:
    commands:
      - zip -r coderunv2.zip ./*
artifacts:
  files:
    - ./coderunv2.zip
