version: 0.2

env:
  variables:
    RAILS_ENV: "development"
            
phases:
  install:
    commands:
      - apt-get update
      - apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
      - gem install bundler
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rspec
      - bundle exec cucumber
