version: 0.2

env:
  variables:
    RAILS_ENV: "development"
            
phases:
  install:
    commands:
      - gem install bundler
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rspec
      - bundle exec cucumber
